djangoWebsite/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from myapp import views
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('index/', views.das, name='das'),
    path('doc/', views.doc, name='doc'),
# --------------------comment---------------------------

    path('addnewpati/',views.addnewpati, name='addnewpati'),
    path('com/',views.detals, name='details'),
    path('com/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('com/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
# ----------------------------Patient--------------------------------
    path('pati/', views.ttpati, name='pati'),
    path('patientnew/', views.patientnew, name='patientnew'),
    path('pati/update/<int:pk>/', views.patient_update, name='patient_update'),
    path('pati/del/<int:pk>/', views.patient_del, name='patient_del'),


#     -------API---------
    path('', include('myapp.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoWebsite/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/', views.api.urls, name='api'),
]

djangoWebsite/myapp/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return self.user.username


class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)
    venue_image = models.ImageField(null=True, blank=True, upload_to="images/")

    class Meta:
        db_table = "tblemployee"


class doctor(models.Model):
    name = models.CharField(max_length=30)
    NameLogin = models.CharField(max_length=255)
    Password = models.CharField(max_length=20)
    Faculty = models.CharField(max_length=255)
    Image = models.ImageField(null=True, blank=True, upload_to='docterImages/')

    def __str__(self):
        return self.NameLogin


class patient(models.Model):
    Name = models.CharField(max_length=30)
    DoctorID = models.ForeignKey(doctor, on_delete=models.CASCADE)
    DateOfBirth = models.DateField(null=True)
    images = models.ImageField(null=True, blank=True, upload_to='PatientImages/')
    ExamDate = models.DateField()

    # class Meta:
    #     db_table = "tbpatient"
    def __str__(self):
        return self.Name


class receptionist(models.Model):
    Name = models.CharField(max_length=30)
    Password = models.CharField(max_length=20)
    NameLogin = models.CharField(max_length=15)

    def __str__(self):
        return self.Name
    #
    # class Meta:
    #     db_table = "tbreceptionist"


class comment(models.Model):
    NameOfDisease = models.CharField(max_length=255)
    PatientID = models.ForeignKey(patient, on_delete=models.CASCADE)
    DoctorID = models.ForeignKey(doctor, on_delete=models.CASCADE)
    InputImage = models.ImageField(null=True, upload_to='InputImages/', blank=True)
    OutputImage = models.ImageField(null=True, upload_to='OutputImages/', blank=True)
    ResultByDoctor = models.TextField()

    def __str__(self):
        return self.NameOfDisease

    # class Meta:
    #     db_table = "tbcomment"


class diseases(models.Model):
    NameDiseases = models.CharField(max_length=255)
    DoctorID = models.ForeignKey(doctor, on_delete=models.CASCADE)
# Create your models here.

djangoWebsite/myapp/forms.py
# //myapp/forms.py
from typing import Type

from django import forms
from myapp.models import Employee, comment, doctor, patient
class EmployeeForm(forms.ModelForm):
    class Meta:
        model: Type[Employee] = Employee

        fields = ['name', 'contact', 'email', 'venue_image']

        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }),
            'email': forms.EmailInput(attrs={ 'class': 'form-control' }),
            'contact': forms.TextInput(attrs={ 'class': 'form-control' }),

      }
class CommentForm(forms.ModelForm):

    class Meta:
        model: Type[comment] = comment
        fields = '__all__'
        widgets = {
            'Date': forms.DateInput(attrs={'type': 'date'}),
        }


class DoctorFrom(forms.ModelForm):
    class Meta:
        model: Type[doctor] = doctor
        fields = '__all__'
        widgets = {

        }

class PatientForm(forms.ModelForm):

    class Meta:

        model: Type[patient] = patient
        fields = '__all__'
        widgets = {
            'DateOfBirth': forms.DateTimeInput(attrs={'type': 'date'}),
            'ExamDate': forms.DateTimeInput(attrs={'type': 'date'}),

        }

djangoWebsite/myapp/views.py
# from django.shortcuts import render

# Create your views here.
# // myapp / views.py

from django.shortcuts import render, redirect, get_object_or_404
from .forms import EmployeeForm, DoctorFrom, PatientForm, CommentForm
from .models import Employee, doctor, patient, comment
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from ninja import NinjaAPI, Form
from .schemas import *
from typing import List


def das(request):
    return render(request, 'base2.html')


def doc(request):
    Doctor = doctor.objects.all()
    return render(request, 'doctor.html', {'Doctor': Doctor})


# -----------------------patient---------------------
def ttpati(request):
    patienter = patient.objects.all()
    return render(request, 'patienter.html', {'patienter': patienter})


def patientnew(request):
    if request.method == 'POST':
        form = PatientForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/pati/')
    else:
        form = PatientForm()
    return render(request, 'create_pati.html', {'form': form})


def patient_update(request, pk):
    patientz = patient.objects.get(pk=pk)
    if request.method == 'POST':
        form = PatientForm(request.POST, request.FILES, instance=patientz)
        if form.is_valid():
            form.save()
            return redirect('/pati/')
    else:
        form = PatientForm(instance=patientz)
    return render(request, 'update_com.html', {'form': form, 'patientz': patientz})


def patient_del(request, pk):
    patienty = get_object_or_404(patient, pk=pk)
    patienty.delete()
    return redirect('/pati/')


# ------------------------
def addnewpati(request):
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, )
        if form.is_valid():
            form.save()
            return redirect('/com/')

    else:
        form = CommentForm()
    return render(request, 'create_item.html', {'form': form})


def detals(request):
    comments = comment.objects.all()
    return render(request, 'item_detail.html', {'comments': comments})


def comment_update(request, pk):
    commentz = comment.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=commentz)
        if form.is_valid():
            form.save()
            return redirect('/com/')
    else:
        form = CommentForm(instance=commentz)
    return render(request, 'update_com.html', {'form': form, 'commentz': commentz})


def comment_delete(request, pk):
    commenty = get_object_or_404(comment, pk=pk)
    commenty.delete()
    return redirect('/com/')


# --------------


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/index/')
        else:
            return render(request, './LoginLogOut/login.html', {'error_message': 'Invalid login credentials.'})
    return render(request, './LoginLogOut/login.html')


@login_required(login_url='login')
def form_view(request):
    return render(request, 'base2.html')


@login_required(login_url='login')
def logout_view(request):
    logout(request)
    return redirect('login')


# ----------

api = NinjaAPI()


@api.get('/data', response=List[PatientIn])
def showdata(request):
    qs = patient.objects.all()
    return qs


@api.get('/list_doctor', response=List[DoctorOut])
def showdoctor(request):
    qs = doctor.objects.all()
    return qs


@api.post('/add_new_patient_api')
def add_patient(request, post_patient: PatientIn = Form(...)):
    # print(new_patient.dict())
    data = post_patient.dict()

    file = request.FILES.get('images')
    new_patient = patient.objects.create(Name=data["Name"],
                                         DoctorID=doctor.objects.get(id=data["DoctorID"]),
                                         DateOfBirth=data["DateOfBirth"],
                                         images=file,
                                         ExamDate=data["ExamDate"])

    return new_patient.id


@api.get('/list_comment', response=List[CommentOut])
def show_comment(request):
    qs = comment.objects.all()
    return qs


@api.post('/add_new_comment_api')
def add_comment(request, new_comment: CommentIn = Form(...)):
    data = new_comment.dict()
    file = request.FILES.get('InputImage')
    file2 = request.FILES.get("OutputImage")
    comment.objects.create(
        NameOfDisease=data['NameOfDisease'],
        DoctorID=doctor.objects.get(id=data['DoctorID']),
        PatientID=patient.objects.get(id=data['PatientID']),
        InputImage=file,
        OutputImage=file2,
        ResultByDoctor=data['ResultByDoctor']
    )

    return {"message": "Done"}

djangoWebsite/myapp/templates/base.html
{#//myapp/templates/base.html#}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{% block title %}{% endblock %}</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>
<link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css"/>
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body>
<div class="container">
 <div class="row">
    <h4>Django Mysql CRUD (Create Read Update Delete) with Datatables</h4>
    {% block content %}{% endblock %}
 </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src = "https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
       }
    );
} );
</script>
</body>
</html>

djangoWebsite/myapp/templates/base2.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
<!--    <link href="{vendor/fontawesome-free/css/all.min.css}" rel="stylesheet" type="text/css">-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/index/">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/doc/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Bác sĩ</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->


            <!-- Nav Item - Pages Collapse Menu -->


            <!-- Nav Item - Utilities Collapse Menu -->




            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Add:</h6>

                        <a class="collapse-item" href="/addnewpati">Thêm thông tin chuẩn đoán</a>
                        <a class="collapse-item" href="/patientnew">Thêm thông tin bệnh nhân</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="/com/">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Bệnh</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="/pati">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables patient</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>




        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->


                        <!-- Nav Item - Messages -->


                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.first_name}}</span>
{#                                <img src="{{ user.profile_image }}" alt="Avatar">#}
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">


                                <form action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-outline-danger " value="Logout">
                                </form>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                {% block content %}{% endblock %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->



        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

djangoWebsite/myapp/templates/create_item.html
{#//myapp/templates/index.html#}
{% extends "base2.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="container-fluid">
    <form method="POST" class="post-form" action='/addnewpati/' enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

djangoWebsite/myapp/templates/create_pati.html
{#//myapp/templates/index.html#}
{% extends "base2.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="container-fluid">
    <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </form>
</div>
{% endblock content %}

djangoWebsite/myapp/templates/doctor.html
{% extends "base2.html" %}

{% block content %}

    <div class="container-fluid">

                    <!-- Page Heading -->


                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Mã nhân viên</th>
                                            <th>Faculty</th>
                                            <th>Image</th>


                                        </tr>
                                    </thead>

                                    <tbody>
                                    {% for doctor in Doctor %}

                                        <tr>
                                            <td>{{ doctor.name}}</td>
                                            <td>{{ doctor.NameLogin}}</td>
                                            <td>{{ doctor.Faculty}}</td>
                                            {% if doctor.Image %}
                                            <td><img src="{{ doctor.Image.url }}"width="300px" height="250px"></td>
                                            {% endif %}


                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
{% endblock content %}

djangoWebsite/myapp/templates/edit.html
{% extends "base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="container">
        <div class="col-12">
            <h3>Update Details</h3>
        </div>
        <div class="mb-3">
            <label>Employee ID:</label>
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>
        </div>
        <div class="mb-3">
            <label>Name:</label>
            <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />
        </div>
        <div class="mb-3">
            <label>Email:</label>
            <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ employee.email }}" />
        </div>
        <div class="mb-3">
            <label>Contact:</label>
            <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ employee.contact }}" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-success btn-lg">Update</button>
        </div>
    </div>
    </form>
{% endblock content %}

djangoWebsite/myapp/templates/index.html
{#//myapp/templates/index.html#}
{% extends "base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/addnew">
    {% csrf_token %}
    <div class="container">
        <div class="col-12">
        <h3>Enter Details</h3>
        </div>

        <div class="mb-3">
            <label>Name:</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label>Email:</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label>Contact:</label>
            {{ form.contact }}
        </div>
        <div class="mb-3">
            <label>Contact:</label>
            {{ form.venue_image }}
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    </form>
</div>
{% endblock content %}

djangoWebsite/myapp/templates/item_detail.html
{% extends 'base2.html' %}
{% block content %}


    <div class="container-fluid">

                    <!-- Page Heading -->


                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Bệnh</th>
                                            <th>Tên bệnh nhân</th>
                                            <th>chuẩn đoán bởi bác sĩ</th>
                                            <th>Image</th>
                                            <th>Ngày</th>
                                            <th>Chức năng</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                    {% for comment in comments %}

                                        <tr>
                                            <td>{{ comment.NameOfDisease}}</td>
                                            <td>{{ comment.PatientID}}</td>
                                            <td>{{ comment.ResultByDoctor}}</td>
                                            {% if comment.InputImage %}
                                            <td><img src="{{ comment.InputImage.url }}"width="300px" height="250px"></td>
                                            {% endif %}
                                            {% if comment.OutputImage %}
                                            <td><img src="{{ comment.OutputImage.url }}"width="300px" height="250px"></td>
                                            {% endif %}
{#                                            <td>{{ comment.Date}}</td>#}
                                            <td>

{#                                                <a href="{% url 'comment_update' comment.id %}" class="btn btn-primary">update</a>#}
                                                <a href="{% url 'comment_delete' comment.id %}" class="btn btn-primary">delete</a>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

{% endblock content %}

djangoWebsite/myapp/templates/patienter.html
{% extends 'base2.html' %}
{% block content %}


    <div class="container-fluid">

                    <!-- Page Heading -->


                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Tên</th>
                                            <th>Bác sĩ khám</th>
                                            <th>ngày tháng năm sinh bệnh nhân</th>
                                            <th>Image</th>
                                            <th>Ngày khám</th>
                                            <th>Salary</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                    {% for patient in patienter %}

                                        <tr>
                                            <td>{{ patient.Name}}</td>
                                            <td>{{ patient.DoctorID}}</td>
                                            <td>{{ patient.DateOfBirth}}</td>
                                            {% if patient.images %}
                                            <td><img src="{{ patient.images.url }}"width="300px" height="250px"></td>
                                            {% endif %}
                                            <td>{{ patient.ExamDate}}</td>
                                            <td><a href="{% url 'patient_del' patient.id %}"  class="btn btn-primary">delete</a></td>
{#                                            <td><a href="{% url 'patient_update' patient.id %}"  class="btn btn-primary">update</a></td>#}

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

{% endblock content %}